import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
const gold = '#f5a623'
const LANGS = ['ro','ru','en','tr','de','pt','pl']
const CMAP = {MD:'ro',RO:'ro',RU:'ru',BY:'ru',KZ:'ru',UA:'ru',UZ:'ru',AM:'ru',AZ:'ru',GE:'ru',TJ:'ru',TM:'ru',KG:'ru',TR:'tr',DE:'de',AT:'de',CH:'de',PT:'pt',BR:'pt',PL:'pl'}
function useLang(){const[lang,setLang]=useState(()=>{const s=localStorage.getItem('wp_lang');return LANGS.includes(s)?s:'ro'});useEffect(()=>{if(localStorage.getItem('wp_lang'))return;const d=async()=>{try{const r=await fetch('https://ipapi.co/json/',{signal:AbortSignal.timeout(3000)});const j=await r.json();const _c=j.country_code;const l=(_c&&_c.length===2)?(CMAP[_c]||'en'):null;if(l){setLang(l);localStorage.setItem('wp_lang',l)}}catch{try{const r2=await fetch('https://api.country.is/',{signal:AbortSignal.timeout(3000)});const j2=await r2.json();const _c2=j2.country;const l2=(_c2&&_c2.length===2)?(CMAP[_c2]||'en'):null;if(l2){setLang(l2);localStorage.setItem('wp_lang',l2)}}catch{}}};d()},[]);return[lang,l=>{setLang(l);localStorage.setItem('wp_lang',l)}]}
const ICONS=[
  ()=><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>,
  ()=><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></svg>,
  ()=><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>,
  ()=><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>,
  ()=><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>,
  ()=><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>,
  ()=><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>,
  ()=><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"/><line x1="7" y1="2" x2="7" y2="22"/><line x1="17" y1="2" x2="17" y2="22"/><line x1="2" y1="12" x2="22" y2="12"/></svg>,
  ()=><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
]
const COLORS=['#f5a623','#60a5fa','#10b981','#f59e0b','#a78bfa','#34d399','#fb7185','#38bdf8','#4ade80']
const T={
  ro:{login:'Conectați-vă',reg:'Înregistrare',start:'ÎNCEPEȚI ACUM',title:'BENEFICIILE',title2:'PROGRAMULUI',sub:'Tot ce ai nevoie pentru a câștiga din audiența ta',items:[['0% comision platformă','WinPartners câștigă din volumul rețelei, nu din comisionul tău. Toți cei 25% de la cazinou vin direct la tine. Fără taxe ascunse, fără deduceri.'],['Comision RevShare 25%','Primiți 25% din pierderile nete ale jucătorilor recomandați pe toată durata activității lor. Fără limită de timp, fără reduceri.'],['Statistici zilnice','Rapoarte complete cu clickuri, înregistrări, depunători și comisioane. Actualizate zilnic.'],['Cod promoțional unic','Cod personalizat legat de dvs. pe viață. Orice jucător care îl folosește rămâne al dvs. permanent.'],['Plăți săptămânale','Plăți garantate săptămânal prin Bitcoin, USDT, Ethereum, Binance Pay, Skrill sau Neteller. Minim $30.'],['Program referrali 3%','Invitați alți bloggeri și câștigați 3% din comisioanele lor pe viață.'],['Manager personal 24/7','Manager dedicat disponibil permanent pe Telegram.'],['Acoperire internațională','Cazinouri disponibile în Moldova, România, Rusia, Ucraina, Kazakhstan și alte țări.'],['Materiale de marketing','Bannere, linkuri și coduri gata de utilizat pentru toate platformele sociale.'],['Transparență totală','Statistici actualizate zilnic. Vedeți exact câți jucători ați adus și cât câștigați.']]},
  ru:{login:'Войти',reg:'Регистрация',start:'НАЧАТЬ СЕЙЧАС',title:'ПРЕИМУЩЕСТВА',title2:'ПРОГРАММЫ',sub:'Всё необходимое для заработка на вашей аудитории',items:[['0% комиссии платформы','WinPartners зарабатывает на объёме сети, а не на твоей комиссии. Все 25% от казино — тебе. Без скрытых сборов.'],['Комиссия RevShare 25%','Получайте 25% от чистых проигрышей привлечённых игроков на протяжении всего времени их активности.'],['Ежедневная статистика','Полные отчёты с кликами, регистрациями, депозитчиками и комиссиями. Обновляется ежедневно.'],['Уникальный промокод','Персональный код привязан к вам навсегда. Любой игрок, использующий его, ваш навсегда.'],['Еженедельные выплаты','Гарантированные еженедельные выплаты через Bitcoin, USDT, Ethereum, Binance Pay, Skrill или Neteller. Минимум $30.'],['Реферальная программа 3%','Приглашайте блогеров и зарабатывайте 3% от их комиссий пожизненно.'],['Личный менеджер 24/7','Выделенный менеджер постоянно доступен в Telegram.'],['Международное покрытие','Казино доступны в России, Украине, Казахстане, Молдове, Румынии и многих других странах.'],['Маркетинговые материалы','Баннеры, ссылки и коды готовы к использованию на всех социальных платформах.'],['Полная прозрачность','Статистика обновляется ежедневно. Вы точно знаете, сколько игроков привлекли и сколько зарабатываете.']]},
  en:{login:'Login',reg:'Register',start:'GET STARTED NOW',title:'PROGRAM',title2:'BENEFITS',sub:'Everything you need to earn from your audience',items:[['0% platform fee','WinPartners earns from network volume, not from your commission. All 25% from the casino goes directly to you. No hidden fees.'],['25% RevShare Commission','Receive 25% of referred players net losses for the entire duration of their activity. Lifetime, no reductions.'],['Daily statistics','Complete reports with clicks, registrations, depositors and commissions. Updated daily.'],['Unique promo code','Personalized code tied to you for life. Any player who uses it is yours permanently.'],['Weekly payments','Guaranteed weekly payments via Bitcoin, USDT, Ethereum, Binance Pay, Skrill or Neteller. Minimum $30.'],['3% Referral program','Invite other bloggers and earn 3% of their commissions for life.'],['Personal manager 24/7','Dedicated manager permanently available on Telegram.'],['International coverage','Casinos available in Moldova, Romania, Russia, Ukraine, Kazakhstan and other countries.'],['Marketing materials','Banners, links and codes ready to use on all social platforms.'],['Full transparency','Statistics updated daily. See exactly how many players you brought and how much you earn.']]},
  tr:{login:'Giriş',reg:'Kayıt',start:'HEMEN BAŞLA',title:'PROGRAM',title2:'AVANTAJLARI',sub:'Kitlenizden kazanmak için ihtiyacınız olan her şey',items:[['%0 platform ücreti','WinPartners ağ hacminden kazanır, senin komisyonundan değil. Kumarhaneden gelen 25%in tamamı doğrudan sana gidiyor.'],['%25 RevShare Komisyon','Yönlendirilen oyuncuların net kayıplarının tüm aktiflik süreleri boyunca %25ini alırsınız. Ömür boyu.'],['Günlük istatistikler','Tıklamalar, kayıtlar, para yatıranlar ve komisyonlarla eksiksiz raporlar.'],['Benzersiz promosyon kodu','Size bağlı kişisel kod. Kullanan her oyuncu sonsuza dek sizindir.'],['Haftalık ödemeler','Bitcoin, USDT, Ethereum, Binance Pay, Skrill veya Neteller ile garantili haftalık ödemeler. Minimum $30.'],['%3 Referans programı','Diğer bloggerleri davet edin ve ömür boyu komisyonlarının %3ünü kazanın.'],['7/24 Kişisel yönetici','Telegramda sürekli erişilebilir özel yönetici.'],['Uluslararası kapsam','Moldavya, Romanya, Rusya, Ukrayna, Kazakistan ve diğer ülkelerde casinolar mevcut.'],['Pazarlama materyalleri','Tüm sosyal platformlarda kullanıma hazır bannerlar, linkler ve kodlar.'],['Tam şeffaflık','İstatistikler günlük güncellenir. Kaç oyuncu getirdiğinizi ve ne kadar kazandığınızı tam olarak görürsünüz.']]},
  de:{login:'Anmelden',reg:'Registrieren',start:'JETZT STARTEN',title:'PROGRAMM',title2:'VORTEILE',sub:'Alles was Sie brauchen um mit Ihrem Publikum zu verdienen',items:[['0% Plattformgebühr','WinPartners verdient am Netzwerkvolumen, nicht an deiner Provision. Alle 25% vom Casino gehen direkt an dich.'],['25% RevShare Provision','Erhalten Sie 25% der Nettoverluste geworbener Spieler während ihrer gesamten Aktivität. Lebenslang.'],['Tägliche Statistiken','Vollständige Berichte mit Klicks, Registrierungen, Einzahlern und Provisionen. Täglich aktualisiert.'],['Einzigartiger Promo-Code','Personalisierter Code dauerhaft mit Ihnen verknüpft. Jeder Spieler der ihn nutzt gehört Ihnen für immer.'],['Wöchentliche Zahlungen','Garantierte wöchentliche Zahlungen per Bitcoin, USDT, Ethereum, Binance Pay, Skrill oder Neteller. Mindestens $30.'],['3% Empfehlungsprogramm','Laden Sie andere Blogger ein und verdienen Sie lebenslang 3% ihrer Provisionen.'],['Persönlicher Manager 24/7','Dedizierter Manager permanent verfügbar auf Telegram.'],['Internationale Abdeckung','Casinos verfügbar in Moldawien, Rumänien, Russland, Ukraine, Kasachstan und anderen Ländern.'],['Marketingmaterialien','Banner, Links und Codes einsatzbereit für alle sozialen Plattformen.'],['Volle Transparenz','Täglich aktualisierte Statistiken. Sehen Sie genau wie viele Spieler Sie gebracht haben und wie viel Sie verdienen.']]},
  pt:{login:'Entrar',reg:'Registrar',start:'COMEÇAR AGORA',title:'BENEFÍCIOS',title2:'DO PROGRAMA',sub:'Tudo o que precisa para ganhar com o seu público',items:[['0% taxa de plataforma','A WinPartners ganha com o volume da rede, não com a tua comissão. Todos os 25% do cassino vão diretamente para ti.'],['Comissão RevShare 25%','Receba 25% das perdas líquidas dos jogadores indicados durante toda a sua atividade. Vitalícia.'],['Estatísticas diárias','Relatórios completos com cliques, registos, depositantes e comissões. Atualizados diariamente.'],['Código promocional único','Código personalizado ligado a si permanentemente. Qualquer jogador que o use é seu para sempre.'],['Pagamentos semanais','Pagamentos semanais garantidos via Bitcoin, USDT, Ethereum, Binance Pay, Skrill ou Neteller. Mínimo $30.'],['Programa de referência 3%','Convide outros bloggers e ganhe 3% das comissões deles para sempre.'],['Gerente pessoal 24/7','Gerente dedicado permanentemente disponível no Telegram.'],['Cobertura internacional','Casinos disponíveis na Moldávia, Roménia, Rússia, Ucrânia, Cazaquistão e outros países.'],['Materiais de marketing','Banners, links e códigos prontos a usar em todas as plataformas sociais.'],['Transparência total','Estatísticas atualizadas diariamente. Veja exatamente quantos jogadores trouxe e quanto ganha.']]},
  pl:{login:'Zaloguj się',reg:'Rejestracja',start:'ZACZNIJ TERAZ',title:'KORZYŚCI',title2:'PROGRAMU',sub:'Wszystko czego potrzebujesz aby zarabiać na swojej publiczności',items:[['0% opłata platformy','WinPartners zarabia na wolumenie sieci, nie na twojej prowizji. Całe 25% z kasyna trafia bezpośrednio do ciebie.'],['Prowizja RevShare 25%','Otrzymuj 25% strat netto poleconych graczy przez cały czas ich aktywności. Dożywotnio.'],['Codzienne statystyki','Pełne raporty z kliknięciami, rejestracjami, deponentami i prowizjami. Aktualizowane codziennie.'],['Unikalny kod promocyjny','Spersonalizowany kod powiązany z Tobą na stałe. Każdy gracz który go użyje jest Twój na zawsze.'],['Tygodniowe wypłaty','Gwarantowane tygodniowe wypłaty przez Bitcoin, USDT, Ethereum, Binance Pay, Skrill lub Neteller. Minimum $30.'],['Program poleceń 3%','Zapraszaj innych blogerów i zarabiaj 3% ich prowizji dożywotnio.'],['Osobisty menedżer 24/7','Dedykowany menedżer stale dostępny na Telegramie.'],['Zasięg międzynarodowy','Kasyna dostępne w Mołdawii, Rumunii, Rosji, Ukrainie, Kazachstanie i innych krajach.'],['Materiały marketingowe','Banery, linki i kody gotowe do użycia na wszystkich platformach społecznościowych.'],['Pełna przejrzystość','Statystyki aktualizowane codziennie. Widzisz dokładnie ilu graczy przyprowadziłeś i ile zarabiasz.']]},
}
function Nav({lang,setL,t,nav}){return(<nav style={{background:'rgba(10,10,15,0.97)',borderBottom:'1px solid rgba(245,166,35,0.12)',padding:'0 1.25rem',display:'flex',alignItems:'center',justifyContent:'space-between',height:60,position:'sticky',top:0,zIndex:100,backdropFilter:'blur(12px)'}}><div onClick={()=>nav('/')} style={{cursor:'pointer',display:'flex',alignItems:'center',gap:8}}><img src="/icons/logo.png" width="26" height="26" alt="W" style={{borderRadius:3}}/><span style={{fontSize:16,fontWeight:900}}><span style={{color:'#fff'}}>WIN</span><span style={{color:gold}}>PARTNERS</span></span></div><div style={{display:'flex',alignItems:'center',gap:4,minWidth:0}}><div style={{display:'flex',gap:2,background:'rgba(255,255,255,0.04)',borderRadius:6,padding:'2px 3px',border:'1px solid rgba(255,255,255,0.07)',overflowX:'auto',scrollbarWidth:'none',flexShrink:1}}>{LANGS.map(l=>(<button key={l} onClick={()=>setL(l)} style={{padding:'3px 5px',fontSize:10,fontWeight:700,cursor:'pointer',border:`1px solid ${lang===l?gold:'transparent'}`,borderRadius:4,background:lang===l?gold:'transparent',color:lang===l?'#000':'rgba(255,255,255,0.45)',flexShrink:0}}>{l.toUpperCase()}</button>))}</div><button onClick={()=>nav('/register')} style={{padding:'5px 10px',fontSize:11,fontWeight:800,cursor:'pointer',border:'none',borderRadius:5,background:gold,color:'#000',textTransform:'uppercase',flexShrink:0,whiteSpace:'nowrap'}}>{t.reg}</button></div></nav>)}
function Footer({nav}){return(<footer style={{background:'#050508',borderTop:'1px solid rgba(245,166,35,0.08)',padding:'1.75rem 1.25rem'}}><div style={{maxWidth:900,margin:'0 auto',display:'flex',flexDirection:'column',alignItems:'center',gap:12,textAlign:'center'}}><div style={{fontSize:16,fontWeight:900}}><span style={{color:'#fff'}}>WIN</span><span style={{color:gold}}>PARTNERS</span></div><div style={{display:'flex',gap:16,flexWrap:'wrap',justifyContent:'center'}}>{[['/',''],['/about','About'],['/benefits','Benefits'],['/faq','FAQ'],['/contact','Contact']].map(([p,l])=>(<span key={p} onClick={()=>nav(p)} style={{fontSize:12,color:'rgba(255,255,255,0.3)',cursor:'pointer'}} onMouseOver={e=>e.target.style.color=gold} onMouseOut={e=>e.target.style.color='rgba(255,255,255,0.3)'}>{l||'Home'}</span>))}</div><div style={{fontSize:11,color:'rgba(255,255,255,0.15)'}}>© 2026 WinPartners</div></div></footer>)}
export default function Benefits(){
  const nav=useNavigate()
  const[lang,setL]=useLang()
  const t=T[lang]||T.ro
  const isMobile=window.innerWidth<768
  return(
    <div style={{background:'#0a0a0f',minHeight:'100vh',color:'#fff',fontFamily:"'Inter',sans-serif",overflowX:'hidden',display:'flex',flexDirection:'column'}}>
      <Nav lang={lang} setL={setL} t={t} nav={nav}/>
      <div style={{background:'linear-gradient(135deg,rgba(245,166,35,0.07) 0%,transparent 65%)',borderBottom:'1px solid rgba(245,166,35,0.08)',padding:isMobile?'2.5rem 1.25rem 2rem':'4rem 2rem 3rem',textAlign:'center',position:'relative',overflow:'hidden'}}>
        <div style={{position:'absolute',top:'50%',left:'50%',transform:'translate(-50%,-50%)',width:500,height:400,background:'radial-gradient(ellipse,rgba(245,166,35,0.05) 0%,transparent 65%)',pointerEvents:'none'}}/>
        <div style={{position:'relative',zIndex:1}}>
          <h1 style={{fontSize:'clamp(2rem,4.5vw,3.5rem)',fontWeight:900,letterSpacing:'.02em',lineHeight:1.05,marginBottom:12}}>{t.title} <span style={{color:gold}}>{t.title2}</span></h1>
          <div style={{width:40,height:3,background:gold,margin:'0 auto 14px',borderRadius:2}}/>
          <p style={{fontSize:15,color:'rgba(255,255,255,0.4)',maxWidth:520,margin:'0 auto'}}>{t.sub}</p>
        </div>
      </div>
      <div style={{maxWidth:1100,margin:'0 auto',padding:isMobile?'2rem 1.25rem':'3.5rem 2rem',flex:1}}>
        <div style={{display:'grid',gridTemplateColumns:isMobile?'1fr':'repeat(auto-fit,minmax(280px,1fr))',gap:14}}>
          {t.items.map(([title,desc],i)=>{
            const Icon=ICONS[i]||ICONS[0]
            const color=COLORS[i]||gold
            return(
              <div key={title} style={{background:'rgba(255,255,255,0.02)',border:'1px solid rgba(255,255,255,0.07)',borderLeft:`3px solid ${color}35`,borderRadius:12,padding:'1.4rem',display:'flex',gap:14,transition:'border-left-color .2s,background .2s'}} onMouseOver={e=>{e.currentTarget.style.borderLeftColor=`${color}70`;e.currentTarget.style.background='rgba(255,255,255,0.03)'}} onMouseOut={e=>{e.currentTarget.style.borderLeftColor=`${color}35`;e.currentTarget.style.background='rgba(255,255,255,0.02)'}}>
                <div style={{width:46,height:46,background:`${color}12`,border:`1px solid ${color}22`,borderRadius:10,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,color}}><Icon/></div>
                <div><div style={{fontSize:14,fontWeight:700,color:'rgba(255,255,255,0.9)',marginBottom:5}}>{title}</div><div style={{fontSize:13,color:'rgba(255,255,255,0.45)',lineHeight:1.65}}>{desc}</div></div>
              </div>
            )
          })}
        </div>
        <div style={{textAlign:'center',marginTop:40}}>
          <button onClick={()=>nav('/register')} style={{padding:'14px 44px',fontSize:14,fontWeight:800,cursor:'pointer',border:'none',borderRadius:7,background:gold,color:'#000',textTransform:'uppercase',letterSpacing:'.05em',boxShadow:'0 6px 28px rgba(245,166,35,0.28)',transition:'box-shadow .15s,transform .1s'}} onMouseOver={e=>{e.currentTarget.style.boxShadow='0 10px 36px rgba(245,166,35,0.4)';e.currentTarget.style.transform='translateY(-1px)'}} onMouseOut={e=>{e.currentTarget.style.boxShadow='0 6px 28px rgba(245,166,35,0.28)';e.currentTarget.style.transform='none'}}>{t.start}</button>
        </div>
      </div>
      <Footer nav={nav}/>
    </div>
  )
}
