import React from 'react'
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
const gold='#f5a623'
const LANGS=['ro','ru','en','tr','de','pt','pl']
const CMAP={MD:'ro',RO:'ro',RU:'ru',BY:'ru',KZ:'ru',UA:'ru',UZ:'ru',AM:'ru',AZ:'ru',GE:'ru',TJ:'ru',TM:'ru',KG:'ru',TR:'tr',DE:'de',AT:'de',CH:'de',PT:'pt',BR:'pt',PL:'pl'}
function useIsMobile(){const[m,setM]=React.useState(window.innerWidth<768);React.useEffect(()=>{const f=()=>setM(window.innerWidth<768);window.addEventListener('resize',f);return()=>window.removeEventListener('resize',f)},[]);return m}
function useLang(){const[lang,setLang]=useState(()=>{const s=localStorage.getItem('wp_lang');return LANGS.includes(s)?s:'ro'});useEffect(()=>{if(localStorage.getItem('wp_lang'))return;const d=async()=>{try{const r=await fetch('https://ipapi.co/json/',{signal:AbortSignal.timeout(3000)});const j=await r.json();const l=CMAP[j.country_code];if(l){setLang(l);localStorage.setItem('wp_lang',l)}}catch{try{const r2=await fetch('https://api.country.is/',{signal:AbortSignal.timeout(3000)});const j2=await r2.json();const l2=CMAP[j2.country];if(l2){setLang(l2);localStorage.setItem('wp_lang',l2)}}catch{}}};d()},[]);return[lang,l=>{setLang(l);localStorage.setItem('wp_lang',l)}]}
function Nav({lang,setL,t,nav}){return(<nav style={{background:'rgba(10,10,15,0.97)',borderBottom:'1px solid rgba(245,166,35,0.12)',padding:'0 1.25rem',display:'flex',alignItems:'center',justifyContent:'space-between',height:60,position:'sticky',top:0,zIndex:100,backdropFilter:'blur(12px)'}}><div onClick={()=>nav('/')} style={{cursor:'pointer',display:'flex',alignItems:'center',gap:8}}><img src="/icons/logo.png" width="26" height="26" alt="W" style={{borderRadius:3}}/><span style={{fontSize:16,fontWeight:900}}><span style={{color:'#fff'}}>WIN</span><span style={{color:gold}}>PARTNERS</span></span></div><div style={{display:'flex',alignItems:'center',gap:4,minWidth:0}}><div style={{display:'flex',gap:2,background:'rgba(255,255,255,0.04)',borderRadius:6,padding:'2px 3px',border:'1px solid rgba(255,255,255,0.07)',overflowX:'auto',scrollbarWidth:'none',flexShrink:1}}>{LANGS.map(l=>(<button key={l} onClick={()=>setL(l)} style={{padding:'3px 5px',fontSize:10,fontWeight:700,cursor:'pointer',border:`1px solid ${lang===l?gold:'transparent'}`,borderRadius:4,background:lang===l?gold:'transparent',color:lang===l?'#000':'rgba(255,255,255,0.45)',flexShrink:0}}>{l.toUpperCase()}</button>))}</div><button onClick={()=>nav('/register')} style={{padding:'5px 10px',fontSize:11,fontWeight:800,cursor:'pointer',border:'none',borderRadius:5,background:gold,color:'#000',textTransform:'uppercase',flexShrink:0,whiteSpace:'nowrap'}}>{t.reg}</button></div></nav>)}
function Footer({nav}){return(<footer style={{background:'#050508',borderTop:'1px solid rgba(245,166,35,0.08)',padding:'1.75rem 1.25rem'}}><div style={{maxWidth:900,margin:'0 auto',display:'flex',flexDirection:'column',alignItems:'center',gap:12,textAlign:'center'}}><div style={{fontSize:16,fontWeight:900}}><span style={{color:'#fff'}}>WIN</span><span style={{color:gold}}>PARTNERS</span></div><div style={{display:'flex',gap:16,flexWrap:'wrap',justifyContent:'center'}}>{[['/',''],['/about','About'],['/benefits','Benefits'],['/faq','FAQ'],['/contact','Contact']].map(([p,l])=>(<span key={p} onClick={()=>nav(p)} style={{fontSize:12,color:'rgba(255,255,255,0.3)',cursor:'pointer'}} onMouseOver={e=>e.target.style.color=gold} onMouseOut={e=>e.target.style.color='rgba(255,255,255,0.3)'}>{l||'Home'}</span>))}</div><div style={{fontSize:11,color:'rgba(255,255,255,0.15)'}}>© 2026 WinPartners</div></div></footer>)}
const T={
  ro:{login:'Conectați-vă',reg:'Înregistrare',back:'← Înapoi',title:'TERMENI ȘI',title2:'CONDIȚII',updated:'Ultima actualizare: Iunie 2026',sections:[['1. Acceptarea termenilor','Prin înregistrarea pe platforma WinPartners, confirmați că ați citit, înțeles și acceptat toți termenii și condițiile prezentate în acest document.'],['2. Eligibilitate','Programul de afiliere WinPartners este deschis persoanelor cu vârsta de minimum 18 ani. Participanții sunt responsabili să respecte legile locale privind jocurile de noroc.'],['3. Comisioane','Partenerii primesc 25% Revenue Share din pierderile nete generate de jucătorii recomandați, pe toată durata activității acestora. Comisionul se plătește săptămânal pentru solduri ce depășesc $30.'],['4. Cod promoțional','Fiecare partener primește coduri promoționale unice. Este interzisă utilizarea codurilor în mod fraudulos sau prin spam. WinPartners poate anula coduri utilizate necorespunzător și poate suspenda contul asociat.'],['5. Plăți','Comisioanele se plătesc săptămânal, cu un sold minim de $30. Metodele acceptate: Bitcoin, USDT, Ethereum, Binance Pay, Skrill, Neteller.'],['6. Conduita partenerului','Partenerii nu pot promova prin spam, publicitate înșelătoare sau conținut destinat minorilor. Nerespectarea duce la suspendarea imediată a contului.'],['7. Confidențialitate','Datele personale sunt stocate și procesate în conformitate cu regulamentul GDPR. Nu vindem și nu distribuim date personale terților fără consimțământul explicit al titularului.'],['8. Modificarea termenilor','WinPartners își rezervă dreptul de a modifica acești termeni cu notificare prealabilă de minimum 7 zile.'],['9. Terminare','WinPartners poate suspenda orice cont care încalcă acești termeni. Soldurile neachitate vor fi plătite în termen de 30 de zile, dacă nu există dispute.'],['10. Politica Cookie','Folosim cookie-uri tehnice esențiale pentru funcționarea platformei. Nu folosim tracking terț fără consimțământ. Poți dezactiva cookie-urile din setările browserului.']]},
  ru:{login:'Войти',reg:'Регистрация',back:'← Назад',title:'УСЛОВИЯ И',title2:'ПОЛОЖЕНИЯ',updated:'Последнее обновление: Июнь 2026',sections:[['1. Принятие условий','Регистрируясь на платформе WinPartners, вы подтверждаете, что прочитали, поняли и приняли все условия и положения данного документа.'],['2. Право участия','Партнёрская программа WinPartners открыта для лиц не моложе 18 лет. Участники обязаны соблюдать местное законодательство в отношении азартных игр.'],['3. Комиссии','Партнёры получают 25% Revenue Share от чистых проигрышей привлечённых игроков на протяжении всего времени их активности. Выплачивается еженедельно при балансе свыше $30.'],['4. Промокод','Каждый партнёр получает уникальные промокоды. Использование кодов мошеннически или спамом запрещено. WinPartners может аннулировать коды и заблокировать аккаунт.'],['5. Выплаты','Комиссии выплачиваются еженедельно при минимальном балансе $30. Методы: Bitcoin, USDT, Ethereum, Binance Pay, Skrill, Neteller.'],['6. Поведение партнёра','Партнёры не могут продвигать через спам, вводящую в заблуждение рекламу или контент для несовершеннолетних. Нарушение — немедленная блокировка аккаунта.'],['7. Конфиденциальность','Персональные данные хранятся и обрабатываются в соответствии с GDPR. Мы не продаём и не передаём персональные данные третьим лицам без явного согласия.'],['8. Изменение условий','WinPartners оставляет за собой право изменять условия с предварительным уведомлением не менее чем за 7 дней.'],['9. Завершение','WinPartners может заблокировать любой аккаунт, нарушающий условия. Непогашенные балансы выплачиваются в течение 30 дней.'],['10. Политика Cookie','Мы используем технические cookie для работы платформы. Мы не используем сторонние трекеры без согласия.']]},
  en:{login:'Login',reg:'Register',back:'← Back',title:'TERMS AND',title2:'CONDITIONS',updated:'Last updated: June 2026',sections:[['1. Acceptance of terms','By registering on the WinPartners platform, you confirm that you have read, understood and accepted all terms and conditions presented in this document.'],['2. Eligibility','The WinPartners affiliate program is open to persons aged 18 and over. Participants are responsible for complying with local laws regarding gambling.'],['3. Commissions','Partners receive 25% Revenue Share of net losses generated by referred players throughout their activity. Paid weekly for balances exceeding $30.'],['4. Promo code','Each partner receives unique promo codes. Using codes fraudulently or through spam is prohibited. WinPartners may cancel improperly used codes and suspend the associated account.'],['5. Payments','Commissions are paid weekly with a minimum balance of $30. Methods: Bitcoin, USDT, Ethereum, Binance Pay, Skrill, Neteller.'],['6. Partner conduct','Partners may not promote through spam, misleading advertising, or content intended for minors. Non-compliance results in immediate account suspension.'],['7. Privacy','Personal data is stored and processed in accordance with GDPR. We do not sell or distribute personal data to third parties without the explicit consent of the holder.'],['8. Modification of terms','WinPartners reserves the right to modify these terms with a minimum of 7 days prior notice.'],['9. Termination','WinPartners may suspend any account that violates these terms. Unpaid balances will be paid within 30 days, if there are no disputes.'],['10. Cookie Policy','We use essential technical cookies for platform functionality. We do not use third-party tracking without consent. You can disable cookies in browser settings.']]},
  tr:{login:'Giriş',reg:'Kayıt',back:'← Geri',title:'KULLANIM',title2:'ŞARTLARI',updated:'Son güncelleme: Haziran 2026',sections:[['1. Koşulların kabulü','WinPartners platformuna kaydolarak bu belgedeki tüm şart ve koşulları okuduğunuzu, anladığınızı ve kabul ettiğinizi onaylarsınız.'],['2. Uygunluk','WinPartners ortaklık programı 18 yaş ve üzeri kişilere açıktır. Katılımcılar yerel kumar mevzuatına uymaktan sorumludur.'],['3. Komisyonlar','Ortaklar, yönlendirilen oyuncuların net kayıplarının tüm aktiflik süreleri boyunca %25ini Revenue Share olarak alır. 30 doların üzerindeki bakiyeler için haftalık ödenir.'],['4. Promosyon kodu','Her ortak benzersiz promosyon kodları alır. Kodların sahte veya spam yoluyla kullanılması yasaktır.'],['5. Ödemeler','Komisyonlar minimum 30 dolar bakiye ile haftalık ödenir. Yöntemler: Bitcoin, USDT, Ethereum, Binance Pay, Skrill, Neteller.'],['6. Ortak davranışı','Ortaklar spam, yanıltıcı reklam veya reşit olmayanlara yönelik içerikle tanıtım yapamaz. Uyumsuzluk hesabın anında askıya alınmasına yol açar.'],['7. Gizlilik','Kişisel veriler GDPRye uygun olarak saklanır ve işlenir. Açık rıza olmaksızın kişisel verileri üçüncü taraflara satmaz veya dağıtmayız.'],['8. Şartların değiştirilmesi','WinPartners en az 7 gün önceden bildirimde bulunarak şartları değiştirme hakkını saklı tutar.'],['9. Sonlandırma','WinPartners şartları ihlal eden hesapları askıya alabilir. Ödenmemiş bakiyeler 30 gün içinde ödenir.'],['10. Çerez Politikası','Platform işlevselliği için temel teknik çerezler kullanıyoruz. İzin olmadan üçüncü taraf takibi kullanmıyoruz.']]},
  de:{login:'Anmelden',reg:'Registrieren',back:'← Zurück',title:'NUTZUNGS-',title2:'BEDINGUNGEN',updated:'Letzte Aktualisierung: Juni 2026',sections:[['1. Annahme der Bedingungen','Mit der Registrierung auf der WinPartners-Plattform bestätigen Sie, dass Sie alle in diesem Dokument enthaltenen Bedingungen gelesen, verstanden und akzeptiert haben.'],['2. Berechtigung','Das WinPartners-Partnerprogramm steht Personen ab 18 Jahren offen.'],['3. Provisionen','Partner erhalten 25% Revenue Share der Nettoverluste geworbener Spieler. Wöchentlich ausgezahlt bei Guthaben über $30.'],['4. Promo-Code','Jeder Partner erhält einzigartige Promo-Codes. Die betrügerische Verwendung oder durch Spam ist verboten.'],['5. Zahlungen','Provisionen werden wöchentlich bei einem Mindestguthaben von $30 ausgezahlt. Methoden: Bitcoin, USDT, Ethereum, Binance Pay, Skrill, Neteller.'],['6. Partnerverhalten','Partner dürfen nicht durch Spam, irreführende Werbung oder Inhalte für Minderjährige werben.'],['7. Datenschutz','Personenbezogene Daten werden gemäß der DSGVO gespeichert und verarbeitet.'],['8. Änderung der Bedingungen','WinPartners behält sich das Recht vor, diese Bedingungen mit mindestens 7 Tagen Vorankündigung zu ändern.'],['9. Kündigung','WinPartners kann jedes Konto sperren das die Bedingungen verletzt. Unbezahlte Guthaben werden innerhalb von 30 Tagen ausgezahlt.'],['10. Cookie-Richtlinie','Wir verwenden technische Cookies für die Plattformfunktionalität. Kein Drittanbieter-Tracking ohne Zustimmung.']]},
  pt:{login:'Entrar',reg:'Registrar',back:'← Voltar',title:'TERMOS E',title2:'CONDIÇÕES',updated:'Última atualização: Junho 2026',sections:[['1. Aceitação dos termos','Ao registar-se na plataforma WinPartners, confirma que leu, compreendeu e aceitou todos os termos e condições apresentados neste documento.'],['2. Elegibilidade','O programa de afiliados WinPartners está aberto a pessoas com 18 anos ou mais.'],['3. Comissões','Os parceiros recebem 25% Revenue Share das perdas líquidas dos jogadores indicados. Pago semanalmente para saldos superiores a $30.'],['4. Código promocional','Cada parceiro recebe códigos promocionais únicos. A utilização fraudulenta ou através de spam é proibida.'],['5. Pagamentos','As comissões são pagas semanalmente com um saldo mínimo de $30. Métodos: Bitcoin, USDT, Ethereum, Binance Pay, Skrill, Neteller.'],['6. Conduta do parceiro','Os parceiros não podem promover através de spam, publicidade enganosa ou conteúdo destinado a menores.'],['7. Privacidade','Os dados pessoais são armazenados e processados de acordo com o RGPD.'],['8. Modificação dos termos','O WinPartners reserva-se o direito de modificar estes termos com um aviso prévio mínimo de 7 dias.'],['9. Rescisão','O WinPartners pode suspender qualquer conta que viole estes termos. Os saldos não pagos serão pagos no prazo de 30 dias.'],['10. Política de Cookies','Usamos cookies técnicos essenciais para o funcionamento da plataforma. Não usamos rastreamento de terceiros sem consentimento.']]},
  pl:{login:'Zaloguj się',reg:'Rejestracja',back:'← Wróć',title:'WARUNKI',title2:'KORZYSTANIA',updated:'Ostatnia aktualizacja: Czerwiec 2026',sections:[['1. Akceptacja warunków','Rejestrując się na platformie WinPartners potwierdzasz, że przeczytałeś, zrozumiałeś i zaakceptowałeś wszystkie warunki korzystania.'],['2. Uprawnienia','Program partnerski WinPartners jest otwarty dla osób powyżej 18 roku życia.'],['3. Prowizje','Partnerzy otrzymują 25% Revenue Share strat netto poleconych graczy. Wypłacane co tydzień dla sald powyżej $30.'],['4. Kod promocyjny','Każdy partner otrzymuje unikalne kody promocyjne. Używanie kodów w sposób oszukańczy lub przez spam jest zabronione.'],['5. Płatności','Prowizje są wypłacane co tydzień przy minimalnym saldzie $30. Metody: Bitcoin, USDT, Ethereum, Binance Pay, Skrill, Neteller.'],['6. Zachowanie partnera','Partnerzy nie mogą promować poprzez spam, wprowadzającą w błąd reklamę lub treści dla nieletnich.'],['7. Prywatność','Dane osobowe są przechowywane i przetwarzane zgodnie z RODO.'],['8. Zmiana warunków','WinPartners zastrzega sobie prawo do zmiany warunków z co najmniej 7-dniowym wyprzedzeniem.'],['9. Zakończenie','WinPartners może zawiesić konto naruszające warunki. Niezapłacone salda zostaną wypłacone w ciągu 30 dni.'],['10. Polityka Cookie','Używamy niezbędnych technicznych plików cookie do działania platformy. Bez śledzenia stron trzecich bez zgody.']]},
}
export default function Terms(){
  const nav=useNavigate()
  const isMobile=useIsMobile()
  const[lang,setL]=useLang()
  const t=T[lang]||T.ro
  return(
    <div style={{background:'#0a0a0f',minHeight:'100vh',color:'#fff',fontFamily:"'Inter',sans-serif",overflowX:'hidden',display:'flex',flexDirection:'column'}}>
      <Nav lang={lang} setL={setL} t={t} nav={nav}/>
      <div style={{background:'linear-gradient(135deg,rgba(245,166,35,0.05) 0%,transparent 60%)',borderBottom:'1px solid rgba(245,166,35,0.07)',padding:'2.5rem 1.25rem 2rem',textAlign:'center'}}>
        <h1 style={{fontSize:'clamp(1.8rem,4vw,3rem)',fontWeight:900,textTransform:'uppercase',letterSpacing:'.02em',marginBottom:8}}>{t.title} <span style={{color:gold}}>{t.title2}</span></h1>
        <div style={{width:36,height:3,background:gold,margin:'0 auto 10px',borderRadius:2}}/>
        <p style={{fontSize:12,color:'rgba(255,255,255,0.3)'}}>{t.updated}</p>
      </div>
      <div style={{maxWidth:820,margin:'0 auto',padding:'2.5rem 1.25rem',flex:1}}>
        {t.sections.map(([title,desc],i)=>(
          <div key={title} style={{marginBottom:0}}>
            {i>0 && <div style={{height:1,background:'rgba(255,255,255,0.05)',margin:'1.5rem 0'}}/>}
            <div style={{display:'flex',gap:14,alignItems:'flex-start'}}>
              <div style={{width:28,height:28,borderRadius:6,background:'rgba(245,166,35,0.1)',border:'1px solid rgba(245,166,35,0.2)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:11,fontWeight:800,color:gold,flexShrink:0,marginTop:2}}>{i+1}</div>
              <div>
                <h3 style={{fontSize:14,fontWeight:700,color:'rgba(255,255,255,0.9)',marginBottom:7}}>{title}</h3>
                <p style={{fontSize:13,color:'rgba(255,255,255,0.5)',lineHeight:1.8,margin:0}}>{desc}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
      <Footer nav={nav}/>
    </div>
  )
}
